-- SM-2: colunas para espaçamento ótimo
ALTER TABLE revisao ADD COLUMN IF NOT EXISTS ef DECIMAL DEFAULT 2.5;
ALTER TABLE revisao ADD COLUMN IF NOT EXISTS intervalo_dias INTEGER DEFAULT 0;
ALTER TABLE revisao ADD COLUMN IF NOT EXISTS repeticao INTEGER DEFAULT 0;
ALTER TABLE revisao ADD COLUMN IF NOT EXISTS proximo_review TIMESTAMP DEFAULT NOW();
